

language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-4.4 g++-4.4
      - clang-3.8
      - nvidia-cuda-toolkit nvidia-cuda-dev

env:
  global:
    - CXX=clang-3.8
  matrix:
    - FEATURES=travis
    - FEATURES=lint