[package]
name = "cumath"
description = "Cuda-based matrix/vector computations"
version = "0.1.11"
repository = "https://github.com/Ltei/cumath"
authors = ["ltei"]
license = "MIT OR Apache-2.0"

build = "build.rs"

[dependencies]
libc = "0.2.39"

[build-dependencies]
cc = "1.0"
